package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Awards generated by hbm2java
 */
@Entity
@Table(name = "awards", catalog = "hibernateCodeMate")
public class Awards implements java.io.Serializable {

	private Integer titleId;
	private String title;
	private byte[] badgePicture;
	private Set<User> users = new HashSet<User>(0);

	public Awards() {
	}

	public Awards(String title) {
		this.title = title;
	}

	public Awards(String title, byte[] badgePicture, Set<User> users) {
		this.title = title;
		this.badgePicture = badgePicture;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TitleID", unique = true, nullable = false)
	public Integer getTitleId() {
		return this.titleId;
	}

	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}

	@Column(name = "Title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "BadgePicture")
	public byte[] getBadgePicture() {
		return this.badgePicture;
	}

	public void setBadgePicture(byte[] badgePicture) {
		this.badgePicture = badgePicture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "awards")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
