package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendarId generated by hbm2java
 */
@Embeddable
public class CalendarId implements java.io.Serializable {

	private Date eventStartDate;
	private Date eventEndDate;
	private String eventName;
	private int userId;

	public CalendarId() {
	}

	public CalendarId(Date eventStartDate, Date eventEndDate, String eventName,
			int userId) {
		this.eventStartDate = eventStartDate;
		this.eventEndDate = eventEndDate;
		this.eventName = eventName;
		this.userId = userId;
	}

	@Column(name = "EventStartDate", nullable = false, length = 19)
	public Date getEventStartDate() {
		return this.eventStartDate;
	}

	public void setEventStartDate(Date eventStartDate) {
		this.eventStartDate = eventStartDate;
	}

	@Column(name = "EventEndDate", nullable = false, length = 19)
	public Date getEventEndDate() {
		return this.eventEndDate;
	}

	public void setEventEndDate(Date eventEndDate) {
		this.eventEndDate = eventEndDate;
	}

	@Column(name = "EventName", nullable = false)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "UserID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalendarId))
			return false;
		CalendarId castOther = (CalendarId) other;

		return ((this.getEventStartDate() == castOther.getEventStartDate())
				|| (this.getEventStartDate() != null
						&& castOther.getEventStartDate() != null
						&& this.getEventStartDate()
								.equals(castOther.getEventStartDate())))
				&& ((this.getEventEndDate() == castOther.getEventEndDate())
						|| (this.getEventEndDate() != null
								&& castOther.getEventEndDate() != null
								&& this.getEventEndDate()
										.equals(castOther.getEventEndDate())))
				&& ((this.getEventName() == castOther.getEventName())
						|| (this.getEventName() != null
								&& castOther.getEventName() != null
								&& this.getEventName()
										.equals(castOther.getEventName())))
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventStartDate() == null ? 0
				: this.getEventStartDate().hashCode());
		result = 37 * result + (getEventEndDate() == null ? 0
				: this.getEventEndDate().hashCode());
		result = 37 * result + (getEventName() == null ? 0
				: this.getEventName().hashCode());
		result = 37 * result + this.getUserId();
		return result;
	}

}
