package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar", catalog = "hibernateCodeMate")
public class Calendar implements java.io.Serializable {

	private CalendarId id;
	private User user;

	public Calendar() {
	}

	public Calendar(CalendarId id, User user) {
		this.id = id;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "eventStartDate", column = @Column(name = "EventStartDate", nullable = false, length = 19)),
			@AttributeOverride(name = "eventEndDate", column = @Column(name = "EventEndDate", nullable = false, length = 19)),
			@AttributeOverride(name = "eventName", column = @Column(name = "EventName", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "UserID", nullable = false)) })
	public CalendarId getId() {
		return this.id;
	}

	public void setId(CalendarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
