package com.beans;
// Generated 8-Nov-2016 10:58:22 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ContestUser generated by hbm2java
 */
@Entity
@Table(name = "contestUser", catalog = "hibernateCodeMate")
@NamedQueries({
		@NamedQuery(name = "ContestUser.check", query = "from ContestUser where contest.contestId = :contestId and user.userId=:userId") })
public class ContestUser implements java.io.Serializable {

	private ContestUserId id;
	private Contest contest;
	private User user;

	public ContestUser() {
	}

	public ContestUser(ContestUserId id, Contest contest, User user) {
		this.id = id;
		this.contest = contest;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contestId", column = @Column(name = "contestID", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "userID", nullable = false)) })
	public ContestUserId getId() {
		return this.id;
	}

	public void setId(ContestUserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contestID", nullable = false, insertable = false, updatable = false)
	public Contest getContest() {
		return this.contest;
	}

	public void setContest(Contest contest) {
		this.contest = contest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
