package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Contestgroup generated by hbm2java
 */
@Entity
@Table(name = "contestgroup", catalog = "hibernateCodeMate")
@NamedQueries({
		@NamedQuery(name = "Contestgroup.getName", query = "select g from Contestgroup c JOIN c.groups g where g.groupName=:groupName"),
		@NamedQuery(name = "Contestgroup.checkIndividual", query = "select g from Contestgroup c JOIN c.groups g Join g.users u where u.userId=:userId and c.contest.contestId=:contestId") })
public class Contestgroup implements java.io.Serializable {

	private ContestgroupId id;
	private Contest contest;
	private Groups groups;
	private int points;

	public Contestgroup() {
	}

	public Contestgroup(ContestgroupId id, Contest contest, Groups groups,
			int points) {
		this.id = id;
		this.contest = contest;
		this.groups = groups;
		this.points = points;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contestId", column = @Column(name = "ContestID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "GroupID", nullable = false)) })
	public ContestgroupId getId() {
		return this.id;
	}

	public void setId(ContestgroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ContestID", nullable = false, insertable = false, updatable = false)
	public Contest getContest() {
		return this.contest;
	}

	public void setContest(Contest contest) {
		this.contest = contest;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GroupID", nullable = false, insertable = false, updatable = false)
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@Column(name = "Points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

}
