package com.beans;
// Generated 8-Nov-2016 10:58:22 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContestUserId generated by hbm2java
 */
@Embeddable
public class ContestUserId implements java.io.Serializable {

	private int contestId;
	private int userId;

	public ContestUserId() {
	}

	public ContestUserId(int contestId, int userId) {
		this.contestId = contestId;
		this.userId = userId;
	}

	@Column(name = "contestID", nullable = false)
	public int getContestId() {
		return this.contestId;
	}

	public void setContestId(int contestId) {
		this.contestId = contestId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContestUserId))
			return false;
		ContestUserId castOther = (ContestUserId) other;

		return (this.getContestId() == castOther.getContestId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContestId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
