package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ForumanswerId generated by hbm2java
 */
@Embeddable
public class ForumanswerId implements java.io.Serializable {

	private int questionId;
	private String answer;
	private int userId;

	public ForumanswerId() {
	}

	public ForumanswerId(int questionId, String answer, int userId) {
		this.questionId = questionId;
		this.answer = answer;
		this.userId = userId;
	}

	@Column(name = "QuestionID", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	@Column(name = "Answer", nullable = false, length = 65535)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "UserID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ForumanswerId))
			return false;
		ForumanswerId castOther = (ForumanswerId) other;

		return (this.getQuestionId() == castOther.getQuestionId())
				&& ((this.getAnswer() == castOther.getAnswer())
						|| (this.getAnswer() != null
								&& castOther.getAnswer() != null
								&& this.getAnswer()
										.equals(castOther.getAnswer())))
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getQuestionId();
		result = 37 * result
				+ (getAnswer() == null ? 0 : this.getAnswer().hashCode());
		result = 37 * result + this.getUserId();
		return result;
	}

}
