package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "hibernateCodeMate")

@NamedQueries({
		@NamedQuery(name = "Groups.getGroup", query = "from Groups where groupName=:groupName"),
		@NamedQuery(name = "Groups.getGroupUsers", query = "from Groups where groupId=:groupId"),
		@NamedQuery(name = "Groups.getUsersGroup", query = "select g from Groups g join g.users u join g.contestgroups cg where u.userId=:userId and cg.contest.contestId=:contestId") })
public class Groups implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private Set<Contestgroup> contestgroups = new HashSet<Contestgroup>(0);
	private Set<Submission> submissions = new HashSet<Submission>(0);
	private Set<User> users = new HashSet<User>(0);

	public Groups() {
	}

	public Groups(String groupName) {
		this.groupName = groupName;
	}

	public Groups(String groupName, Set<Contestgroup> contestgroups,
			Set<Submission> submissions, Set<User> users) {
		this.groupName = groupName;
		this.contestgroups = contestgroups;
		this.submissions = submissions;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GroupID", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "GroupName", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Contestgroup> getContestgroups() {
		return this.contestgroups;
	}

	public void setContestgroups(Set<Contestgroup> contestgroups) {
		this.contestgroups = contestgroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<Submission> getSubmissions() {
		return this.submissions;
	}

	public void setSubmissions(Set<Submission> submissions) {
		this.submissions = submissions;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "groupmember", catalog = "hibernateCodeMate", joinColumns = {
			@JoinColumn(name = "GroupID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "UserID", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
