package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "hibernateCodeMate")
public class Images implements java.io.Serializable {

	private Integer imageId;
	private byte[] image;
	private Set<Tutorial> tutorials = new HashSet<Tutorial>(0);

	public Images() {
	}

	public Images(byte[] image) {
		this.image = image;
	}

	public Images(byte[] image, Set<Tutorial> tutorials) {
		this.image = image;
		this.tutorials = tutorials;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ImageID", unique = true, nullable = false)
	public Integer getImageId() {
		return this.imageId;
	}

	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	@Column(name = "Image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "imageses")
	public Set<Tutorial> getTutorials() {
		return this.tutorials;
	}

	public void setTutorials(Set<Tutorial> tutorials) {
		this.tutorials = tutorials;
	}

}
