package com.beans;
// Generated 5-Nov-2016 11:07:12 PM by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Testcases generated by hbm2java
 */
@Entity
@Table(name = "testcases", catalog = "hibernateCodeMate")
@NamedQueries({
		@NamedQuery(name = "Testcases.getData", query = "from Testcases where testcaseId = :testcaseId"),
		@NamedQuery(name = "Testcases.getInputData", query = "select t from Testcases t JOIN t.problems p where t.type=:testcaseType and p.problemId=:problemId") })
public class Testcases implements java.io.Serializable {

	private Integer testcaseId;
	private Problems problems;
	private String input;
	private String output;
	private String type;

	public Testcases() {
	}

	public Testcases(Problems problems, String input, String output,
			String type) {
		this.problems = problems;
		this.input = input;
		this.output = output;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "testcaseID", unique = true, nullable = false)
	public Integer getTestcaseId() {
		return this.testcaseId;
	}

	public void setTestcaseId(Integer testcaseId) {
		this.testcaseId = testcaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "problemID", nullable = false)
	public Problems getProblems() {
		return this.problems;
	}

	public void setProblems(Problems problems) {
		this.problems = problems;
	}

	@Column(name = "input", nullable = false, length = 65535)
	public String getInput() {
		return this.input;
	}

	public void setInput(String input) {
		this.input = input;
	}

	@Column(name = "output", nullable = false, length = 65535)
	public String getOutput() {
		return this.output;
	}

	public void setOutput(String output) {
		this.output = output;
	}

	@Column(name = "type", nullable = false, length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
